name: Atlas Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          clang++ -dynamiclib -std=c++17 \
          -framework Foundation -framework UIKit -framework Metal -framework QuartzCore \
          Atlas.mm imgui/*.cpp \
          -I./ -I./imgui \
          -o AtlasExecutor.dylib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Atlas-Final-Dylib
          path: AtlasExecutor.dylib
